# Pour les Agents Windows

export AGENT_IP="<AGENT_IP>"
export BUILD_RESOURCE_GROUP_NAME="<BUILD_RESOURCE_GROUP_NAME>"
export ARM_RESOURCE_LOCATION="<ARM_RESOURCE_LOCATION>"
export ARM_RESOURCE_GROUP="<ARM_RESOURCE_GROUP>"
export ARM_OBJECT_ID="<ARM_OBJECT_ID>"
export PRIVATE_VIRTUAL_NETWORK_WITH_PUBLIC_IP="<PRIVATE_VIRTUAL_NETWORK_WITH_PUBLIC_IP>"
export TEMP_RESOURCE_GROUP_NAME="<TEMP_RESOURCE_GROUP_NAME>"
export VNET_NAME="<VNET_NAME>"
export VNET_RESOURCE_GROUP="<VNET_RESOURCE_GROUP>"
export VNET_SUBNET="<VNET_SUBNET>"