# Pour les agents Linux

setx BUILD_RESOURCE_GROUP_NAME '<BUILD_RESOURCE_GROUP_NAME>'
setx DOCKERHUB_LOGIN '<DOCKERHUB_LOGIN>'
setx DOCKERHUB_PASSWORD '<DOCKERHUB_PASSWORD>'
setx ARM_RESOURCE_LOCATION '<ARM_RESOURCE_LOCATION>'
setx ARM_RESOURCE_GROUP '<ARM_RESOURCE_GROUP>'
setx TEMP_RESOURCE_GROUP_NAME '<TEMP_RESOURCE_GROUP_NAME>'
setx VNET_NAME '<VNET_NAME>'
setx VNET_RESOURCE_GROUP '<VNET_RESOURCE_GROUP>'
setx VNET_SUBNET '<VNET_SUBNET>'